# Auto-generated by version_manager.py - DO NOT EDIT
"""OpenSims构建信息"""

__version__ = "1.0.3.1"
__short_version__ = "1.0.3"
__build_date__ = "2026-04-05T19:43:32.287775"
__build_number__ = 1

def get_version_info():
    """返回版本信息字典"""
    return {
        "version": __version__,
        "short_version": __short_version__,
        "build_date": __build_date__,
        "build_number": __build_number__
    }
