#!/usr/bin/env python3
"""
OpenSims 版本管理器
自动递增版本号并生成版本信息文件
"""

import os
import json
import datetime
from typing import Tuple

VERSION_FILE = 'version.json'

class VersionManager:
    """版本管理器"""

    def __init__(self, version_file=VERSION_FILE):
        self.version_file = version_file
        self.version_data = self._load_version()

    def _load_version(self) -> dict:
        """加载版本信息"""
        if os.path.exists(self.version_file):
            with open(self.version_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        else:
            # 初始版本
            return {
                "major": 1,
                "minor": 0,
                "patch": 0,
                "build": 0,
                "last_updated": datetime.datetime.now().isoformat(),
                "changelog": []
            }

    def _save_version(self):
        """保存版本信息"""
        with open(self.version_file, 'w', encoding='utf-8') as f:
            json.dump(self.version_data, f, ensure_ascii=False, indent=2)

    @property
    def current_version(self) -> str:
        """获取当前版本字符串 (如 1.0.0.123)"""
        v = self.version_data
        return f"{v['major']}.{v['minor']}.{v['patch']}.{v['build']}"

    @property
    def short_version(self) -> str:
        """获取短版本字符串 (如 1.0.0)"""
        v = self.version_data
        return f"{v['major']}.{v['minor']}.{v['patch']}"

    def increment_build(self, changelog: str = "") -> str:
        """
        递增build号（每次打包调用）
        返回新版本号
        """
        self.version_data['build'] += 1
        self.version_data['last_updated'] = datetime.datetime.now().isoformat()

        if changelog:
            self.version_data['changelog'].insert(0, {
                "version": self.current_version,
                "date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "changes": changelog
            })
            # 只保留最近10条
            self.version_data['changelog'] = self.version_data['changelog'][:10]

        self._save_version()
        return self.current_version

    def bump_patch(self, changelog: str = ""):
        """递增patch号（功能更新）"""
        self.version_data['patch'] += 1
        self.version_data['build'] = 0
        self.increment_build(changelog)

    def bump_minor(self, changelog: str = ""):
        """递增minor号（新功能）"""
        self.version_data['minor'] += 1
        self.version_data['patch'] = 0
        self.version_data['build'] = 0
        self.increment_build(changelog)

    def bump_major(self, changelog: str = ""):
        """递增major号（重大更新）"""
        self.version_data['major'] += 1
        self.version_data['minor'] = 0
        self.version_data['patch'] = 0
        self.version_data['build'] = 0
        self.increment_build(changelog)

    def get_version_info(self) -> dict:
        """获取完整版本信息"""
        return {
            "version": self.current_version,
            "short_version": self.short_version,
            "build_date": self.version_data['last_updated'],
            "changelog": self.version_data.get('changelog', [])
        }

    def generate_build_info_py(self, output_path='build_info.py'):
        """生成build_info.py供代码导入"""
        content = f'''# Auto-generated by version_manager.py - DO NOT EDIT
"""OpenSims构建信息"""

__version__ = "{self.current_version}"
__short_version__ = "{self.short_version}"
__build_date__ = "{self.version_data['last_updated']}"
__build_number__ = {self.version_data['build']}

def get_version_info():
    """返回版本信息字典"""
    return {{
        "version": __version__,
        "short_version": __short_version__,
        "build_date": __build_date__,
        "build_number": __build_number__
    }}
'''
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[Version] 生成构建信息: {output_path}")
        return output_path


def get_version() -> str:
    """快速获取当前版本号（供其他模块调用）"""
    vm = VersionManager()
    return vm.current_version


def get_build_info() -> dict:
    """获取构建信息"""
    vm = VersionManager()
    return vm.get_version_info()


if __name__ == "__main__":
    import sys

    vm = VersionManager()

    if len(sys.argv) < 2:
        print(f"当前版本: {vm.current_version}")
        print("\n命令:")
        print("  python version_manager.py show         显示当前版本")
        print("  python version_manager.py build       递增build号（自动打包）")
        print("  python version_manager.py patch [msg] 递增patch号")
        print("  python version_manager.py minor [msg] 递增minor号")
        print("  python version_manager.py major [msg] 递���major号")
        print("  python version_manager.py gen         生成build_info.py")
        sys.exit(0)

    cmd = sys.argv[1]
    changelog = ' '.join(sys.argv[2:]) if len(sys.argv) > 2 else ""

    if cmd == 'show':
        print(vm.current_version)
        print(f"短版本: {vm.short_version}")
        print(f"Build: {vm.version_data['build']}")
        print(f"更新时间: {vm.version_data['last_updated']}")

    elif cmd == 'build':
        new_ver = vm.increment_build(changelog or "Auto build")
        print(f"[Build] 递增build号: {vm.current_version}")

    elif cmd == 'patch':
        vm.bump_patch(changelog or "Patch release")
        print(f"[Patch] 新版本: {vm.current_version}")

    elif cmd == 'minor':
        vm.bump_minor(changelog or "Minor release")
        print(f"[Minor] 新版本: {vm.current_version}")

    elif cmd == 'major':
        vm.bump_major(changelog or "Major release")
        print(f"[Major] 新版本: {vm.current_version}")

    elif cmd == 'gen':
        vm.generate_build_info_py()
        print("[Gen] build_info.py 已生成")

    else:
        print(f"未知命令: {cmd}")
        sys.exit(1)
